// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package acme_endpoint

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AuthorizationBehavior, b.ko.Spec.AuthorizationBehavior) {
		delta.Add("Spec.AuthorizationBehavior", a.ko.Spec.AuthorizationBehavior, b.ko.Spec.AuthorizationBehavior)
	} else if a.ko.Spec.AuthorizationBehavior != nil && b.ko.Spec.AuthorizationBehavior != nil {
		if *a.ko.Spec.AuthorizationBehavior != *b.ko.Spec.AuthorizationBehavior {
			delta.Add("Spec.AuthorizationBehavior", a.ko.Spec.AuthorizationBehavior, b.ko.Spec.AuthorizationBehavior)
		}
	}
	if len(a.ko.Spec.CertificateTags) != len(b.ko.Spec.CertificateTags) {
		delta.Add("Spec.CertificateTags", a.ko.Spec.CertificateTags, b.ko.Spec.CertificateTags)
	} else if len(a.ko.Spec.CertificateTags) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.CertificateTags, b.ko.Spec.CertificateTags) {
			delta.Add("Spec.CertificateTags", a.ko.Spec.CertificateTags, b.ko.Spec.CertificateTags)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Contact, b.ko.Spec.Contact) {
		delta.Add("Spec.Contact", a.ko.Spec.Contact, b.ko.Spec.Contact)
	} else if a.ko.Spec.Contact != nil && b.ko.Spec.Contact != nil {
		if *a.ko.Spec.Contact != *b.ko.Spec.Contact {
			delta.Add("Spec.Contact", a.ko.Spec.Contact, b.ko.Spec.Contact)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
